//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCoverExplorer.MSBuildTasks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.$safeprojectname$.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCoverExplorer.MSBuildTasks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents of config file:\r\n{0}.
        /// </summary>
        internal static string NCoverConfigContent {
            get {
                return ResourceManager.GetString("NCoverConfigContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents of config file:\r\n{0}.
        /// </summary>
        internal static string NCoverExplorerConfigContent {
            get {
                return ResourceManager.GetString("NCoverExplorerConfigContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting config file: {0}.
        /// </summary>
        internal static string NCoverExplorerDeletingConfig {
            get {
                return ResourceManager.GetString("NCoverExplorerDeletingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This line cannot be parsed: &apos;{0}&apos;. Coverage exclusions should be in format: Type=Pattern (e.g. &apos;Assembly=*.Tests&apos;).
        /// </summary>
        internal static string NCoverExplorerInvalidExclusion {
            get {
                return ResourceManager.GetString("NCoverExplorerInvalidExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the registry key for NCoverExplorer indicating the program location (set by installing with TestDriven.Net). Please specify the full path to NCoverExplorer.Console.exe using the ToolPath attribute..
        /// </summary>
        internal static string NCoverExplorerNotFound {
            get {
                return ResourceManager.GetString("NCoverExplorerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find NCover.Console.exe in C:\Program Files\NCover\. Specify an alternate path using the ToolPath attribute on your NCover target..
        /// </summary>
        internal static string NCoverNotFound {
            get {
                return ResourceManager.GetString("NCoverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected NCover.Console v{0} in {1}.
        /// </summary>
        internal static string NCoverVersionFound {
            get {
                return ResourceManager.GetString("NCoverVersionFound", resourceCulture);
            }
        }
    }
}
